### ISSUE TITLE
Api 24

### ISSUE THREAD

**Issue by T8RIN** [GIGAMOLE/ComposeShadowsPlus#1]
why did this lib needs api 24, why not using api 21 ?

**Comment by T8RIN** [comment]
I've overriden this in manifest and all looks fine, so can you set it to 21 instead of 24 please?

**Comment by GIGAMOLE** [comment]
Hi, thanks for this issue, I will try to fix it after two weeks, I am currently on vacation.

**Comment by T8RIN** [comment]
Okay 🐸

**Comment by GIGAMOLE** [comment]
Done. 1.0.3 version ready.
