### ISSUE TITLE
Clipped shadows

### ISSUE THREAD

**Issue by T8RIN** [GIGAMOLE/ComposeShadowsPlus#2]
Will this lib provide clipped shadows like [shadow-gadgets](https://github.com/zed-alpha/shadow-gadgets) do ?

**Comment by GIGAMOLE** [comment]
Done. New release: [1.0.4](https://github.com/GIGAMOLE/ComposeShadowsPlus/releases/tag/1.0.4).

Check it out here: https://github.com/GIGAMOLE/ComposeShadowsPlus

**Comment by T8RIN** [comment]
> Done. New release: [1.0.4](https://github.com/GIGAMOLE/ComposeShadowsPlus/releases/tag/1.0.4).
> 
> Check it out here: https://github.com/GIGAMOLE/ComposeShadowsPlus

Thanks :)

**Comment by T8RIN** [comment]
Also, can't it be done for rsblur?

**Comment by GIGAMOLE** [comment]
Its ready for RSBlur, SoftLayer and Elevation.

**Comment by T8RIN** [comment]
But this seems to be working only with special container?(

**Comment by GIGAMOLE** [comment]
It's for the Elevation. Check the sample. Maybe you are using it wrong.

**Comment by T8RIN** [comment]
Got it thanks!
